
spring:
  application:
    name: products-service

#Declarar ip del servidor Eureka si esta en diferente maquina
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8001

path:
  products: /api/products

